[package]
name = "example"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
frooxengine-rs = { version = "*", path = "../../bindings/rust/frooxengine-rs" }
